@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":changePasswordCommandParser" as changePasswordCommandParser LOGIC_COLOR
participant "c:changePasswordCommand" as changePasswordCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box PasswordManager MODEL_COLOR_T1
participant ":PasswordManager" as PasswordManager MODEL_COLOR
end box

[-> LogicManager : execute("changePassword op/oldPW1 np/newPW2")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("changePassword op/oldPW1 np/newPW2")
activate AddressBookParser

create changePasswordCommandParser
AddressBookParser -> changePasswordCommandParser
activate changePasswordCommandParser

changePasswordCommandParser --> AddressBookParser
deactivate changePasswordCommandParser

AddressBookParser -> changePasswordCommandParser : parse("op/oldPW1 np/newPW2")
activate changePasswordCommandParser

create changePasswordCommand
changePasswordCommandParser -> changePasswordCommand
activate changePasswordCommand

changePasswordCommand --> changePasswordCommandParser : c
deactivate changePasswordCommand

changePasswordCommandParser --> AddressBookParser : c
deactivate changePasswordCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
changePasswordCommandParser -[hidden]-> AddressBookParser
destroy changePasswordCommandParser

AddressBookParser --> LogicManager : c
deactivate AddressBookParser

LogicManager -> changePasswordCommand : execute(model)
activate changePasswordCommand

changePasswordCommand -> PasswordManager : check("oldPW1")
activate PasswordManager

PasswordManager --> changePasswordCommand

changePasswordCommand -> PasswordManager : set("newPW2")

PasswordManager --> changePasswordCommand

create CommandResult
changePasswordCommand -> CommandResult
activate CommandResult

CommandResult --> changePasswordCommand
deactivate CommandResult

changePasswordCommand --> LogicManager : result
deactivate changePasswordCommand

[<--LogicManager
deactivate LogicManager
@enduml
