@@author LuahJunYang
@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":FilterPolicyDescriptionCommandParser" as FilterPolicyDescriptionCommandParser LOGIC_COLOR
participant "f :FilterPolicyDescriptionCommand" as FilterPolicyDescriptionCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[->LogicManager : execute(filterpolicydescription cancer plans)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(filterpolicydescription cancer plans)
activate AddressBookParser

create FilterPolicyDescriptionCommandParser
AddressBookParser -> FilterPolicyDescriptionCommandParser:
activate FilterPolicyDescriptionCommandParser

FilterPolicyDescriptionCommandParser --> AddressBookParser
deactivate FilterPolicyDescriptionCommandParser

AddressBookParser -> FilterPolicyDescriptionCommandParser : parse(cancer plans)
activate FilterPolicyDescriptionCommandParser

create FilterPolicyDescriptionCommand
FilterPolicyDescriptionCommandParser -> FilterPolicyDescriptionCommand
activate FilterPolicyDescriptionCommand

FilterPolicyDescriptionCommand --> FilterPolicyDescriptionCommandParser: f
deactivate FilterPolicyDescriptionCommand

FilterPolicyDescriptionCommandParser --> AddressBookParser: f
deactivate FilterPolicyDescriptionCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar'
FilterPolicyDescriptionCommandParser -[hidden]-> AddressBookParser
destroy FilterPolicyDescriptionCommandParser

AddressBookParser --> LogicManager: f
deactivate AddressBookParser

LogicManager -> FilterPolicyDescriptionCommand : execute()
activate FilterPolicyDescriptionCommand

FilterPolicyDescriptionCommand -> Model : updateFilteredPerson(Predicate)
activate Model
Model -> Model : getFilteredPersonList()
Model --> FilterPolicyDescriptionCommand
deactivate Model
LogicManager <- FilterPolicyDescriptionCommand: result
deactivate FilterPolicyDescriptionCommand
@enduml
