@startuml
'https://plantuml.com/sequence-diagram

box Logic
participant ":LogicManager" as LogicManager
participant ":AddressBookParser" as AddressBookParser
participant ":GroupMeetingCommandParser" as GroupMeetingCommandParser
participant ":GroupMeetingCommand" as GroupMeetingCommand
end box

autonumber
[->LogicManager : execute(groupmeeting west)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(groupmeeting west)
activate AddressBookParser

create GroupMeetingCommandParser
AddressBookParser -> GroupMeetingCommandParser:
activate GroupMeetingCommandParser

GroupMeetingCommandParser --> AddressBookParser
GroupMeetingCommandParser -> GroupMeetingCommandParser : Parse

create GroupMeetingCommand
GroupMeetingCommandParser -> GroupMeetingCommand
activate GroupMeetingCommand
LogicManager -> GroupMeetingCommand : execute()
deactivate GroupMeetingCommandParser

GroupMeetingCommand -> Model : updateFilteredPerson(Predicate)
activate Model
Model -> Model : getFilteredPersonList()
Model --> GroupMeetingCommand
deactivate Model
LogicManager <- GroupMeetingCommand: result
deactivate GroupMeetingCommand

box Model
participant ":Model" as Model
end box
@enduml
