@startuml
'https://plantuml.com/sequence-diagram
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":GroupMeetingCommandParser" as GroupMeetingCommandParser LOGIC_COLOR
participant "g :GroupMeetingCommand" as GroupMeetingCommand LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[->LogicManager : execute(groupmeeting west)
activate LogicManager

LogicManager -> AddressBookParser : parseCommand(groupmeeting west)
activate AddressBookParser

create GroupMeetingCommandParser
AddressBookParser -> GroupMeetingCommandParser:
activate GroupMeetingCommandParser

GroupMeetingCommandParser --> AddressBookParser
deactivate GroupMeetingCommandParser

AddressBookParser -> GroupMeetingCommandParser : parse(west)
activate GroupMeetingCommandParser

create GroupMeetingCommand
GroupMeetingCommandParser -> GroupMeetingCommand
activate GroupMeetingCommand

GroupMeetingCommand --> GroupMeetingCommandParser: g
deactivate GroupMeetingCommand

GroupMeetingCommandParser --> AddressBookParser: g
deactivate GroupMeetingCommandParser
'Hidden arrow to position the destroy marker below the activation bar'
GroupMeetingCommandParser -[hidden]-> AddressBookParser
destroy GroupMeetingCommandParser

AddressBookParser --> LogicManager: g
deactivate AddressBookParser
LogicManager -> GroupMeetingCommand : execute()
activate GroupMeetingCommand

GroupMeetingCommand -> Model : updateFilteredPerson(Predicate)
activate Model
Model -> Model : getFilteredPersonList()
Model --> GroupMeetingCommand
deactivate Model
LogicManager <- GroupMeetingCommand: result
deactivate GroupMeetingCommand

@enduml
